#!/usr/bin/env bash

# Build images for all services.
docker-compose -f build/openresty/docker-compose.yml build --no-cache \
&& docker-compose -f build/mariadb/docker-compose.yml build --no-cache \
&& docker-compose -f build/php-fpm/docker-compose.yml build --no-cache \
&& docker-compose -f build/php-cli/docker-compose.yml build --no-cache \
&& docker-compose -f build/drush/docker-compose.yml build --no-cache \
&& docker-compose -f build/xhprof/docker-compose.yml build --no-cache \
&& docker-compose up -d \
&& docker-compose ps
