#!/bin/bash

export ENVIRONMENT=dev

export PROJECT_ROOT="./run/example"

# Location to mount into the containers (php-fpm, nginx, drush).
export PROJECT_DEST="/app"

# - "/home/${USER}/Projects/app:/app"

# The WSL instance where VS Code Remote points to.
# The WSL instance must have PHP and XDebug installed.
# On WSL distributions, usually it's the eth0 result of ifconfig.
export XDEBUG_REMOTE_HOST=172.27.233.110

# If the shell running docker compose is the WSL host for VSC and XDebug:
# ifconfig eth0 | grep "inet " | awk -F'[: ]+' '{ print $4 }'
# https://unix.stackexchange.com/a/87470/5626

case $1 in

  "start")
    ./scripts/start.sh
    ;;

  "stop")
    ./scripts/stop.sh
    ;;

  # You can use restart instead of destroy to update mounts.
  "restart")
    ./scripts/stop.sh
    ./scripts/start.sh
    ;;

  "drush")
    shift;
    ./scripts/drush.sh "$@"
    ;;

  "destroy")
    ./scripts/destroy.sh
    ;;

  *)
    docker-compose ps
    ;;
esac
